%% SummarizeSessionData
% load Unit data and summarized into session data

ClassifyUnits;
clearvars -except Unit

%% Load Other Data

BNBResult = load('D:\Data\Lobster\BNB_Result.mat');
DistanceResultPath = 'D:\Data\Lobster\FineDistanceResult';

%% Make into a table

Sessions = table(...
    unique(Unit.Session),...
    zeros(40,1),...
    zeros(40,1),...
    zeros(40,1),...
    zeros(40,1), zeros(40,1),...
    zeros(40,1), zeros(40,1), zeros(40,1),...
    zeros(40,1), zeros(40,1), zeros(40,1),...
    zeros(40,1), zeros(40,1), zeros(40,1),...
    zeros(40,1),...
    'VariableNames',...
        ["Session",...
        "BNB_HW_Accuracy",...
        "BNB_HW_CrossEntropy",...
        "Location_Error",...
        "N_HE1", "N_HE2",...
        "N_HW1", "N_HW2", "N_HW3",...
        "N_HWA1", "N_HWA2", "N_HWA3",...
        "N_HWE1", "N_HWE2", "N_HWE3",...
        "NumCell"]...
    );

for i_session = 1 : 40
    session = Sessions.Session(i_session);
    
    Sessions.BNB_HW_Accuracy(i_session) = BNBResult.result{i_session}.balanced_accuracy_HWAE(2);
    Sessions.BNB_HW_CrossEntropy(i_session) = BNBResult.result{i_session}.CrossEntropy_HWAE;
    
    LocationResult = load(fullfile(DistanceResultPath, strcat(session, 'result_distance.mat')), 'WholeTestResult');

    % L1 Error of True / L1 Error of the shuffled
    % 1 = No difference between original vs shuffled
    % 0.5 = Half of the error compared to the shuffled
    % 0 = Zero error
    Sessions.Location_Error(i_session) = ...
        mean(abs(LocationResult.WholeTestResult(:, 3) - LocationResult.WholeTestResult(:, 5)))...
        / mean(abs(LocationResult.WholeTestResult(:, 3) - LocationResult.WholeTestResult(:, 4))); 
    

    Sessions.N_HE1(i_session) = sum(Unit.Session == session &  Unit.Group_HE == 1);
    Sessions.N_HE2(i_session)= sum(Unit.Session == session &  Unit.Group_HE == 2);

    Sessions.N_HW1(i_session) = sum(Unit.Session == session &  Unit.Group_HW == 1);
    Sessions.N_HW2(i_session) = sum(Unit.Session == session &  Unit.Group_HW == 2);
    Sessions.N_HW3(i_session) = sum(Unit.Session == session &  Unit.Group_HW == 3);

    Sessions.N_HWA1(i_session) = sum(Unit.Session == session &  Unit.Group_HW_A == 1);
    Sessions.N_HWA2(i_session) = sum(Unit.Session == session &  Unit.Group_HW_A == 2);
    Sessions.N_HWA3(i_session) = sum(Unit.Session == session &  Unit.Group_HW_A == 3);

    Sessions.N_HWE1(i_session) = sum(Unit.Session == session &  Unit.Group_HW_E == 1);
    Sessions.N_HWE2(i_session) = sum(Unit.Session == session &  Unit.Group_HW_E == 2);
    Sessions.N_HWE3(i_session) = sum(Unit.Session == session &  Unit.Group_HW_E == 3);

    Sessions.NumCell(i_session) = sum(Unit.Session == session);
end
