function data = readAnymazeData(path)
%% readAnymazeData
% Read csv position file generated by ANY-MAZE and check if the file format is correct

data = readtable(path,'PreserveVariableNames', true);

%% Check table format
if size(data, 2) ~= 3
    error('readAnymazeData : csv file does not contain 3 columns (time, head X, head Y');
end

if ~ isequal(data.Properties.VariableNames, {'Time', 'Head position X', 'Head position Y'})
    error('readAnymazeData : check the export option.');
end

data = table2array(data);
data = data(2:end,:);
end